### ISSUE TITLE
코드 실행 후 예시 테스트케이스 통과 여부 확인

### ISSUE THREAD

**Issue by acisliver** [NaKaLiGoBa/AlgoWithMe-FE#11]

**Comment by gukin-han** [comment]
- [x] 작성 중인 코드를 로컬에 저장
- [x] 테스트 코드 실행 api 작성
- [x] 버튼 클릭 핸들러 작성
- [x] 결과에 따른 조건부 UI 반영

### 조건부에 따른 UI 예시
![Screenshot 2023-10-29 at 8 05 57 AM](https://github.com/NaKaLiGoBa/AlgoWithMe-FE/assets/115940366/eaf9a652-8c06-4b79-afce-06daf4d266f6)
![Screenshot 2023-10-29 at 8 06 38 AM](https://github.com/NaKaLiGoBa/AlgoWithMe-FE/assets/115940366/cf51868d-a539-4cb3-ab1f-3b6be20f47ca)

### 로컬 스토리지에 작성 코드 저장
<img width="1161" alt="Screenshot 2023-10-29 at 9 31 02 AM" src="https://github.com/NaKaLiGoBa/AlgoWithMe-FE/assets/115940366/9444a487-8b28-45a1-af4d-61aff70a2bed">
