### ISSUE TITLE
코드 제출 후 정답 여부 확인

### ISSUE THREAD

**Issue by acisliver** [NaKaLiGoBa/AlgoWithMe-FE#12]

**Comment by gukin-han** [comment]
- [x] 제출 버튼 api 작성
- [x] 결과를 가져와서 alert창 띄우기
<img width="1292" alt="Screenshot 2023-10-29 at 11 40 24 AM" src="https://github.com/NaKaLiGoBa/AlgoWithMe-FE/assets/115940366/2807bb18-e212-43df-a9eb-c28612451138">
